
import { Transaction } from './types';

export const CATEGORIES = [
  'Alimentación',
  'Transporte',
  'Vivienda',
  'Entretenimiento',
  'Salud',
  'Suscripciones',
  'Regalos',
  'Salario',
  'Inversiones',
  'Ahorro',
  'Otros'
];

export const INCOME_CATEGORIES = [
  'Salario',
  'Inversiones',
  'Regalos',
  'Otros'
];

export const EXPENSE_CATEGORIES = [
  'Alimentación',
  'Transporte',
  'Vivienda',
  'Entretenimiento',
  'Salud',
  'Suscripciones',
  'Regalos',
  'Inversiones',
  'Ahorro',
  'Otros'
];

// No longer used directly, generated dynamically in onboarding
export const INITIAL_TRANSACTIONS: Transaction[] = [];

// Neon palette for Dark Mode
export const COLORS = [
  '#00E396', // Neon Green
  '#008FFB', // Bright Blue
  '#FEB019', // Gold/Yellow
  '#FF4560', // Neon Red
  '#775DD0', // Purple
  '#03A9F4', // Light Blue
  '#4CAF50', // Green
  '#F9CE1D', // Yellow
  '#FF9800'  // Orange
];

export const RECURRING_ITEMS = [
  { id: 'salary', label: 'Salario Mensual', type: 'income', category: 'Salario', defaultAmount: 2500, icon: '💰' },
  { id: 'rent', label: 'Alquiler / Hipoteca', type: 'expense', category: 'Vivienda', defaultAmount: 800, icon: '🏠' },
  { id: 'utilities', label: 'Internet / Luz / Agua', type: 'expense', category: 'Vivienda', defaultAmount: 100, icon: '💡' },
  { id: 'streaming', label: 'Suscripciones', type: 'expense', category: 'Suscripciones', defaultAmount: 15, icon: '🎬' },
  { id: 'savings', label: 'Ahorro Mensual', type: 'expense', category: 'Ahorro', defaultAmount: 200, icon: '💸' },
];

export const TRANSLATIONS = {
  es: {
    dashboard: "Inicio",
    data: "Análisis",
    aiCoach: "Chat",
    balance: "Balance Neto",
    income: "Ingresos", // Changed to match term
    expenses: "Gastos", // Changed to match term
    recentActivity: "Actividad Reciente",
    noActivity: "No hay actividad registrada.",
    breakdown: "Desglose de Gastos",
    monthlyPerformance: "Rendimiento Mensual",
    savingsEvolution: "Evolución del Ahorro",
    totalSavings: "Ahorro Total",
    investmentPerformance: "Rendimiento Inversiones",
    netInvestment: "Neto Inversiones",
    invested: "Invertido",
    returned: "Retorno",
    viewGeneral: "General",
    viewSavings: "Ahorro",
    viewInvestments: "Inversiones",
    noData: "Sin datos",
    newEntry: "Nueva Entrada",
    save: "Guardar",
    cancel: "Cancelar",
    description: "Nombre de transacción", // Changed per request
    amount: "Cantidad", // Changed per request
    category: "Categoría",
    type: "Tipo",
    date: "Fecha",
    settings: "Configuración",
    theme: "Tema",
    language: "Idioma",
    currency: "Moneda",
    dark: "Oscuro",
    light: "Claro",
    aiIntro: "Optimización de Rendimiento Financiero",
    aiScan: "Escanear Finanzas",
    aiThinking: "Thinking Mode analiza patrones complejos.",
    aiSearch: "Inteligencia de mercado en tiempo real.",
    aiVision: "Visualización de objetivos.",
    generate: "Generar",
    analyzing: "Analizando...",
    sources: "Fuentes de Datos",
    placeholderDesc: "Ej: Spotify, Uber...",
    placeholderAdvice: "Estrategia para ahorrar 10k...",
    placeholderSearch: "Tasas de interés actuales...",
    placeholderImage: "Apartamento loft moderno...",
    good: "Bien",
    load: "Carga",
    vsLast: "vs anterior",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    email: "Correo Electrónico",
    password: "Contraseña",
    name: "Nombre",
    continueGoogle: "Continuar con Google",
    dontHaveAccount: "¿No tienes cuenta?",
    haveAccount: "¿Ya tienes cuenta?",
    logout: "Cerrar Sesión",
    welcome: "Bienvenido",
    guest: "Invitado",
    errorUserExists: "El usuario ya existe.",
    errorInvalidCreds: "Credenciales inválidas.",
    errorGeneric: "Ocurrió un error.",
    successRegister: "Registro exitoso.",
    chatPlaceholder: "Pregunta sobre tus gastos, ej: ¿En qué gasto más?",
    chatWelcome: "Hola. Soy tu asistente financiero. Analizo tus transacciones para darte respuestas precisas.",
    you: "Tú",
    assistant: "Asistente",
    landingTitle: "Desbloquea tu Potencial Financiero",
    landingSubtitle: "Monitorización de gastos y analítica de alto rendimiento.",
    exportData: "Exportar CSV",
    importData: "Importar CSV",
    dataManagement: "Gestión de Datos",
    fileUploaded: "Archivo importado correctamente.",
    fileError: "Error al leer el archivo. Verifica el formato.",
    // Onboarding
    obWelcome: "Bienvenido a FinanzaPro",
    obSubtitle: "Tu sistema operativo financiero personal.",
    obStart: "Comenzar Configuración",
    obNameTitle: "¿Cómo te llamas?",
    obNamePlaceholder: "Tu Nombre",
    obNext: "Siguiente",
    obPhotoTitle: "Personaliza tu perfil",
    obPhotoSubtitle: "Sube una foto o continúa por ahora.",
    obUpload: "Subir Foto",
    obSkip: "Omitir",
    obRecurTitle: "Automaticemos esto",
    obRecurSubtitle: "Selecciona los ingresos o gastos que tienes todos los meses.",
    obFinish: "Finalizar Configuración",
    obInitializing: "Inicializando Sistema...",
    obAnalyzing: "Analizando patrones...",
    obConfiguring: "Configurando base de datos...",
    // Date Ranges
    dateRange: "Rango de Fechas",
    allTime: "Todo",
    thisMonth: "Este Mes",
    lastMonth: "Mes Pasado",
    last3Months: "Últimos 3 Meses",
    last6Months: "Últimos 6 Meses",
    yearToDate: "Este Año",
    lastYear: "Año Pasado",
    custom: "Personalizado",
    startDate: "Fecha Inicio",
    endDate: "Fecha Fin",
    apply: "Aplicar",
    // Dashboard Ranges
    dashboardConfig: "Vista del Dashboard",
    rangeAnnual: "Anual",
    range15Days: "Últimos 15 días",
    range30Days: "Últimos 30 días",
    rangePaycheck: "Última Nómina",
    noRecurringData: "No tenemos datos registrados",
  },
  en: {
    dashboard: "Monitor",
    data: "Data",
    aiCoach: "Chat",
    balance: "Net Balance",
    income: "Income",
    expenses: "Expenses",
    recentActivity: "Recent Activity",
    noActivity: "No activity recorded.",
    breakdown: "Expense Breakdown",
    monthlyPerformance: "Monthly Performance",
    savingsEvolution: "Savings Evolution",
    totalSavings: "Total Savings",
    investmentPerformance: "Investment Performance",
    netInvestment: "Net Investments",
    invested: "Invested",
    returned: "Returned",
    viewGeneral: "General",
    viewSavings: "Savings",
    viewInvestments: "Investments",
    noData: "No data",
    newEntry: "New Entry",
    save: "Save",
    cancel: "Cancel",
    description: "Transaction Name", // Aligned
    amount: "Amount", // Aligned
    category: "Category",
    type: "Type",
    date: "Date",
    settings: "Settings",
    theme: "Theme",
    language: "Language",
    currency: "Currency",
    dark: "Dark",
    light: "Light",
    aiIntro: "Financial Performance Optimization",
    aiScan: "Scan Finances",
    aiThinking: "Thinking Mode analyzes complex patterns.",
    aiSearch: "Real-time market intelligence.",
    aiVision: "Goal Visualization.",
    generate: "Generate",
    analyzing: "Analyzing...",
    sources: "Data Sources",
    placeholderDesc: "Ex: Spotify, Uber...",
    placeholderAdvice: "Strategy to save 10k...",
    placeholderSearch: "Current interest rates...",
    placeholderImage: "Modern loft apartment...",
    good: "Good",
    load: "Load",
    vsLast: "vs last",
    login: "Log In",
    signup: "Sign Up",
    email: "Email",
    password: "Password",
    name: "Name",
    continueGoogle: "Continue with Google",
    dontHaveAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    logout: "Reset App",
    welcome: "Welcome",
    guest: "Guest",
    errorUserExists: "User already exists.",
    errorInvalidCreds: "Invalid credentials.",
    errorGeneric: "An error occurred.",
    successRegister: "Registration successful.",
    chatPlaceholder: "Ask about your spending, ex: Where do I spend the most?",
    chatWelcome: "Hello. I am your financial assistant. I analyze your transactions to give you precise answers.",
    you: "You",
    assistant: "Assistant",
    landingTitle: "Unlock Your Financial Potential",
    landingSubtitle: "High-performance expense tracking and analytics.",
    exportData: "Export CSV",
    importData: "Import CSV",
    dataManagement: "Data Management",
    fileUploaded: "File imported successfully.",
    fileError: "Error reading file.",
    // Onboarding
    obWelcome: "Welcome to FinanzaPro",
    obSubtitle: "Your personal financial operating system.",
    obStart: "Start Setup",
    obNameTitle: "What's your name?",
    obNamePlaceholder: "Your Name",
    obNext: "Next",
    obPhotoTitle: "Customize your profile",
    obPhotoSubtitle: "Upload a photo or skip for now.",
    obUpload: "Upload Photo",
    obSkip: "Skip",
    obRecurTitle: "Let's automate this",
    obRecurSubtitle: "Select the income or expenses you have every month.",
    obFinish: "Finish Setup",
    obInitializing: "Initializing System...",
    obAnalyzing: "Analyzing patterns...",
    obConfiguring: "Configuring database...",
    // Date Ranges
    dateRange: "Date Range",
    allTime: "All Time",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    last3Months: "Last 3 Months",
    last6Months: "Last 6 Months",
    yearToDate: "Year to Date",
    lastYear: "Last Year",
    custom: "Custom",
    startDate: "Start Date",
    endDate: "End Date",
    apply: "Apply",
    // Dashboard Ranges
    dashboardConfig: "Dashboard View",
    rangeAnnual: "Annual",
    range15Days: "Last 15 Days",
    range30Days: "Last 30 Days",
    rangePaycheck: "Last Paycheck",
    noRecurringData: "No data recorded",
  }
};
